version: "3.7"

services:
  # refers to customers service 
  customers: 
    build: .
    command: sh -c "node customers"
    ports: # replaces -dp 3000:3000
      - 5000:5000

    working_dir: /CustomersService
    volumes:
    # we cd into books service so we need to leave it in this docker compose...
      - ../CustomersService/:/CustomersService

    environment:  
      CUSTOMERS_MONGO_URI: mongodb://mongodb_customers:27017/customers
    links:
      - mongodb_customers

  mongodb_customers:
    image: mongo:latest

    # NOTE: ports are designated as HOST:CONTAINER
    ports: # 27018:27017 as 27017:27017 may be used by books service 
      - 27018:27017
    volumes:
      - customers_mongodb_data_container:/data/db

volumes:
  customers_mongodb_data_container:
  
